// ============================================================
// siteData.ts — AUTO-GENERATED by site_generator.py
// Do not edit manually. Re-run the generator to update.
// ============================================================

export type Variant = 'A' | 'B' | 'C' | 'D'

export interface ServiceItem {
  iconName: string
  name: string
  description: string
}

export interface ReviewItem {
  name: string
  rating: number
  text: string
  date: string
}

export interface WhyUsPoint {
  heading: string
  body: string
}

export interface ProcessStep {
  heading: string
  body: string
}

export interface FAQItem {
  question: string
  answer: string
}

export interface SiteData {
  businessName: string
  instagramUrl?: string
  facebookUrl?: string
  trade: string
  tagline: string
  phone: string
  email: string
  address: string
  city: string
  serviceArea: string
  googleBusinessUrl: string
  yearsExperience: number
  bookingUrl?: string
  logoUrl?: string
  photos: string[]
  variant: Variant
  hero: {
    heading: string
    subheading: string
    primaryCta: string
    secondaryCta: string
  }
  services: ServiceItem[]
  trustItems: string[]
  whyUs: {
    heading: string
    subheading: string
    points: WhyUsPoint[]
  }
  process: ProcessStep[]
  faqs: FAQItem[]
  about: {
    heading: string
    body: string
    ownerName: string
  }
  reviews: ReviewItem[]
  seo: {
    title: string
    description: string
    canonicalUrl: string
  }
}

const siteData: SiteData = {
  businessName: 'TnT Roofing Services Bristol',
  trade: 'Roofers',
  tagline: 'Bristol\'s Trusted Roofing Experts',
  phone: '+44 7938 109894',
  email: 'info@tnt-roofing.co.uk',
  address: '13 Harbury Rd, Henleaze, Bristol BS9 4PN, United Kingdom',
  city: 'Bristol',
  serviceArea: 'Bristol',
  googleBusinessUrl: 'https://www.google.com/maps/search/?api=1&query=TnT%20Roofing%20Services%20Bristol&query_place_id=ChIJ7eynGrRIuE0RAyoi8IHGW9w',
  instagramUrl: 'https://www.instagram.com/aiwithdennis',
  facebookUrl: 'https://www.facebook.com/leadplug/',
  yearsExperience: 0,
  logoUrl: 'https://tnt-roofing.co.uk/wp-content/uploads/2025/01/cropped-Favicon-180x180.png',
  photos: ["https://tnt-roofing.co.uk/wp-content/uploads/2024/04/roofing-installations-480x320.jpg", "https://tnt-roofing.co.uk/wp-content/uploads/2024/04/Best-Local-Roofer-480x320.jpg", "https://tnt-roofing.co.uk/wp-content/uploads/2024/04/Roof-Repairs-Near-Me-480x320.jpg", "https://tnt-roofing.co.uk/wp-content/uploads/2024/04/How-to-Repair-a-Roof-1024x683.jpg", "https://tnt-roofing.co.uk/wp-content/uploads/2024/04/tiled-roofing-leadwork-400x400.jpg", "https://tnt-roofing.co.uk/wp-content/uploads/2024/04/Slate-Roofing-Experts-400x400.jpg", "https://tnt-roofing.co.uk/wp-content/uploads/2024/04/chimney-repointing-400x400.jpg", "https://tnt-roofing.co.uk/wp-content/uploads/2024/04/leadwork-roofing-400x400.jpg"],

  variant: 'B',

  hero: {
    heading: 'Professional Roofers Serving Bristol and Surrounding Areas',
    subheading: 'TnT Roofing Services Bristol provides reliable roofing solutions for homes and businesses across Bristol. Our skilled team offers quality workmanship with 24/7 availability and a commitment to customer satisfaction.',
    primaryCta: 'Get a Free Quote',
    secondaryCta: 'Call Now',
  },

  services: [
    {
      iconName: 'Roof',
      name: 'Roof Repairs',
      description: 'We fix all types of roof damage including missing tiles, leaks, and storm damage. Our prompt response ensures your property stays protected from the elements.',
    },
    {
      iconName: 'RefreshCw',
      name: 'Roof Replacement',
      description: 'Complete roof replacement using quality materials and expert installation techniques. We handle everything from planning to completion with minimal disruption to your daily routine.',
    },
    {
      iconName: 'Droplets',
      name: 'Leak Detection',
      description: 'Professional leak detection and repair services to protect your property from water damage. We use advanced techniques to locate and fix leaks quickly and effectively.',
    },
    {
      iconName: 'Shield',
      name: 'Roof Maintenance',
      description: 'Regular maintenance services to keep your roof in excellent condition year-round. Our preventative approach helps avoid costly repairs and extends your roof\'s lifespan.',
    },
    {
      iconName: 'Home',
      name: 'Guttering Services',
      description: 'Complete gutter installation, repair, and cleaning services to protect your property\'s foundations. We ensure proper water drainage and prevent damage from blocked or damaged gutters.',
    },
    {
      iconName: 'Search',
      name: 'Roof Inspections',
      description: 'Thorough roof inspections to assess condition and identify potential issues before they become major problems. We provide detailed reports with recommendations and cost estimates.',
    },
  ],

  trustItems: [
    'Fully Insured',
    'Free Quotes',
    'Local to Bristol',
    '24/7 Response'
  ],

  whyUs: {
    heading: 'Why Choose TnT Roofing Services Bristol?',
    subheading: 'We\'re a local Bristol roofing company committed to delivering exceptional service and quality workmanship that you can trust.',
    points: [
      {
        heading: 'Local Experts',
        body: 'Based in Bristol, we understand local weather conditions and building requirements. Our team knows the area well and provides personalised service to our neighbours.',
      },
      {
        heading: 'Quality Materials',
        body: 'We only use high-grade materials from trusted suppliers to ensure lasting results. Every job is completed to the highest standards with attention to detail.',
      },
      {
        heading: 'Rapid Response',
        body: 'Available 24/7 for emergency roofing issues that can\'t wait. We understand that roof problems need immediate attention to prevent further damage.',
      },
      {
        heading: 'Transparent Pricing',
        body: 'Clear, honest quotes with no hidden costs or surprises. We explain all work required and provide fair pricing for every project.',
      },
    ],
  },

  process: [
    {
      heading: 'Contact Our Team',
      body: 'Get in touch by phone or email to discuss your roofing needs. We\'ll arrange a convenient time to assess your property and understand your requirements.',
    },
    {
      heading: 'Free Assessment',
      body: 'Our experienced roofers will inspect your roof and provide a detailed evaluation. We\'ll explain any issues found and discuss the best solutions for your situation.',
    },
    {
      heading: 'Detailed Quote',
      body: 'Receive a comprehensive written quote outlining all work, materials, and costs involved. We ensure you understand exactly what\'s included before any work begins.',
    },
    {
      heading: 'Expert Installation',
      body: 'Our skilled team completes your roofing project efficiently and safely with minimal disruption. We clean up thoroughly and ensure you\'re completely satisfied with the finished work.',
    },
  ],

  faqs: [
    {
      question: 'How quickly can you respond to emergency roof repairs?',
      answer: 'We offer 24/7 emergency response for urgent roofing issues. Our team can typically attend emergency callouts within hours to secure your property and prevent further damage.',
    },
    {
      question: 'Do you provide free quotes for roofing work?',
      answer: 'Yes, we provide free, no-obligation quotes for all roofing projects. Our detailed assessments include a thorough inspection and clear explanation of any work required.',
    },
    {
      question: 'What areas of Bristol do you cover?',
      answer: 'We serve Bristol and the surrounding areas including all suburbs and nearby towns. Contact us to confirm we cover your specific location for your roofing project.',
    },
    {
      question: 'Are you fully insured for roofing work?',
      answer: 'Yes, we carry comprehensive public liability insurance and all necessary trade insurances. This protects both our team and your property during any roofing work we undertake.',
    },
    {
      question: 'What types of roofing materials do you work with?',
      answer: 'We work with all common roofing materials including tiles, slates, felt, EPDM, and metal roofing systems. Our team has expertise across traditional and modern roofing solutions.',
    },
    {
      question: 'Can you help with insurance claims for roof damage?',
      answer: 'We can assist with insurance claims by providing detailed reports and evidence of damage. Our documentation helps support your claim and ensures repairs meet insurance requirements.',
    },
  ],

  about: {
    heading: 'About TnT Roofing Services Bristol',
    body: 'I founded TnT Roofing Services Bristol to provide honest, reliable roofing services to homeowners and businesses across our great city. Having lived and worked in Bristol for many years, I understand how our local weather can affect roofs, and I\'m committed to helping my neighbours protect their properties with quality workmanship and fair pricing.',
    ownerName: 'The TnT Roofing Team — Owner',
  },

  reviews: [
    {
      name: 'Jordan',
      rating: 5,
      text: 'Brilliant service very knowledgeable and very polite and welcoming never forced anything we didn\'t want would highly recommend brilliant service.',
      date: '',
    },
    {
      name: 'joshua l.',
      rating: 5,
      text: 'Came out quickly and provided a detailed quote and was more than happy with the quality of work great job done',
      date: '',
    },
    {
      name: 'Teresa G.',
      rating: 5,
      text: 'TNT Roofing were brilliant!  James came and gave us a quote, scaffolding went up, roof materials were delivered, team arrived and did the roof, mess cleared away and scaffolding down the next day. Beautiful job, professionally done, quick, efficient and quiet! We would highly recommend TNT.',
      date: '',
    },
    {
      name: 'Emma M.',
      rating: 5,
      text: 'Very professional and efficient service, great price and amazing communication during the whole process! Our house roof is now brand new and the attention to details makes it even better. So so pleased with everything. Highly recommended!!!\n\n(p.s. comment coming from a high expectations kind of person)',
      date: '',
    },
    {
      name: 'Alistair W.',
      rating: 5,
      text: 'TNT were excellent. A swift visit and quote, then on time and hard working completing a number of roof and gutter jobs, with a good end of day clean up.  Thank you and strongly recommend.',
      date: '',
    },
  ],

  seo: {
    title: 'TnT Roofing Services Bristol | Roofers in Bristol',
    description: 'Professional roofers in Bristol offering repairs, replacements & maintenance. 24/7 emergency response, free quotes, fully insured. Call +44 7938 109894 today.',
    canonicalUrl: 'https://preview-tnt-roofing-services-bristol.vercel.app',
  },
}

export default siteData

// CSS custom properties injected by site_generator.py
// These override :root variables in index.css at runtime
export const siteTheme = {
  '--color-primary':  '#1C1C1E',
  '--color-accent':   '#E85D26',
  '--color-bg':       '#F9F9F9',
  '--color-text':     '#1A1A1A',
  '--color-muted':    '#6B7280',
  '--color-border':   '#E4E4E4',
  '--font-heading':   "'Instrument Serif', Georgia, serif",
  '--font-body':      "'DM Sans', system-ui, sans-serif",
}
